[line_break]
disabled = false

[character]
success_symbol = '[âœ](bold green)'
error_symbol = '[âœ](bold red)'

[os]
disabled = false
format = "$symbol "

[os.symbols]
Windows = "ğŸªŸ"
Ubuntu = "ğŸ¯"

[username]
format = "[â–“](#a3aed2)[ $user ](fg:#090c0c bg:#a3aed2)[î‚°](fg:#a3aed2 bg:#DA627D)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$hostname ](fg:#090c0c bg:#DA627D)[î‚°](fg:#DA627D)ğŸ’» "
disabled = false

[directory]
truncation_length = 4
truncation_symbol = "â€¦/"
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "fg:#090c0c bg:#769ff0"
format = "[ ï±® $path ]($style)"

[cmd_duration]
min_time = 4000
show_milliseconds = false
disabled = false
style = "bold italic #87A752"
format = ' â³ [$duration]($style) '

[git_branch]
symbol = " ó°Š¤ "
format = "[$symbol$branch ](fg:#1C3A5E bg:#FCF392)"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
format = '( [\[$all_status$ahead_behind\]]($style) )'


[conda]
format = "î˜† [$environment](bold gree)"
ignore_base = false

[nodejs]
format = " [ï¢˜ $version](bold red) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[package]
disabled = true
